dependencies {
    implementation project(':usecase')
    implementation project(':model')
    implementation project(':extract-data')
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'
}